### PR TITLE
output_file: link the last frame

### PR DESCRIPTION
**Pull request by dvv**
Link the last frame in ringbuffer as frame.jpg efficiently. The rationale is to have the last frame at constant location without spawning a shell for each frame.
If it is welcome, please consider exposing a parameter to control this behavior (say, `--link frame.jpg` to specify both the will to link the last frame and its filename).
TIA

### CODE REVIEW

**Comment by jacksonliam** [comment]
Yeah I think putting it on an option is best, other people might not be expecting the extra 'file' to suddenly start appearing in their output directory!

**Comment by dvv** [comment]
@jacksonliam I updated PR to have `-l FILENAME` option. Please consider applying

**Comment by jacksonliam** [comment]
Thanks, looks good now, merged! (Sorry for the delay!)

**Comment by dvv** [comment]
\o/

**Pull request merged**
