### PR TITLE
Add support for UYVY format and fix code for reporting wrong format

### PR DESCRIPTION
**Pull request by droberg**
Some changes necessary to use with STK1160. Feel free to comment an make suggestions for changes.

### CODE REVIEW

**Comment by jacksonliam** [comment]
Looks fine to me! 

Have you tested the changes with any jpeg or yuv cam just to make sure there's no regression?

**Comment by droberg** [comment]
At least partly.
I dont have a yuv camera but I have tried using a mpeg variant. The way things are setup it is impossible to get a format that the driver does not support so I cannot test it directly without manipulating the code.  

Maybe there  is a loopback-variant that I can use to try it out...

**Comment by droberg** [comment]
I found a way to test it using "vivi" https://www.linuxtv.org/wiki/index.php/VIVI

The vivi module had support for both YUV UYVY and MPEG and they all work as expected

**Comment by jacksonliam** [comment]
Thanks for that! Great work!

**Comment by Nandox7** [comment]
Is there a way to pass on the pixelformat after this patch?
With it I can't run the plugin as I keep getting:

"MJPG Streamer Version.: 2.0
 i: Using V4L2 device.: /dev/video0
 i: Desired Resolution: 640 x 480
 i: Frames Per Second.: -1
 i: Format............: JPEG
 i: TV-Norm...........: DEFAULT
 i: Could not obtain the requested pixelformat, got: Test
 Init v4L2 failed !! exit fatal
 i: init_VideoIn failed

**Comment by jacksonliam** [comment]
@Nandox7 yes this PR adds the -u flag you need if you have a device which requires uyvy format. 

@droberg that error message isn't very helpful and has the word 'Test' in it. 
Perhaps 'The device doesn't support the requested pixel format, try the -y or -u flag'

**Comment by droberg** [comment]
Oh, I see... I misunderstood the question completely.

The error message was supposed to translate the obtained pixelformat to a
string and "Test" was just a placeholder. I will have a look to see if
there is something available in v4l to achieve this or change to something
better.

@Nandox7 <https://github.com/Nandox7> what hardware do you have? (Do you
know the pixelformat) What cmd-line did you pass? I will try to simulate
the error.  Chances are that this occurs when there are no supported
variants.

Regards Per
Den 17 juli 2016 9:36 em skrev "jacksonliam" <notifications@github.com>:

**Comment by Nandox7** [comment]
Thanks both for the reply.

@droberg the webcam is a old Creative labs Live!
ID 041e:4036 Creative Technology, Ltd Webcam Live!/Live! Pro

I used the code from the previous commit and it is working correctly now.
It would be good to also update the output of the **--help** flag for the plugin, I did tried
that to see if there was a flag to pass the pixelformat but none was listed.

**Comment by brunh** [comment]
Hello,
i was following your instruction to install your product - mjpg-streamer-experimental - but unfortunately, i wasn't able to get streaming with chipsets 007 and stk1160. i get only white screen. 
when i use standard mode with chipset 007i can see frame jerking, with stk1160 i get green and purple image.
i tried all values taht i could find, changed resolution, assigned atributes -t pal/ntsc - but sreen is still just white.

_./mjpg_streamer -i "./input_uvc.so -d /dev/video0 -y -f 4" -o "./output_http.so -w ./www -p 9000"_

_./mjpg_streamer -i "./input_uvc.so -d /dev/video0 -y -f 4 -r 720x576 -n -t pal" -o "./output_http.so -w ./www -p 9000"_

root@raspberrypi:~/mjpg-streamer-code/mjpg-streamer-experimental# ./start.sh
MJPG Streamer Version: svn rev: 3:182M
 DBG(input_uvc.c, input_init(), 136): argv[0]=UVC webcam grabber
 DBG(input_uvc.c, input_init(), 136): argv[1]=-d
 DBG(input_uvc.c, input_init(), 136): argv[2]=/dev/video0
 DBG(input_uvc.c, input_init(), 136): argv[3]=-y
 DBG(input_uvc.c, input_init(), 136): argv[4]=-f
 DBG(input_uvc.c, input_init(), 136): argv[5]=4
 DBG(input_uvc.c, input_init(), 136): argv[6]=-r
 DBG(input_uvc.c, input_init(), 136): argv[7]=720x576
 DBG(input_uvc.c, input_init(), 136): argv[8]=-n
 DBG(input_uvc.c, input_init(), 136): argv[9]=-t
 DBG(input_uvc.c, input_init(), 136): argv[10]=pal
 DBG(input_uvc.c, input_init(), 194): case 2,3
 DBG(input_uvc.c, input_init(), 231): case 8,9
 DBG(input_uvc.c, input_init(), 223): case 6,7
 DBG(input_uvc.c, input_init(), 201): case 4,5
 DBG(input_uvc.c, input_init(), 253): case 14,15
 DBG(input_uvc.c, input_init(), 287): case 19,20
 DBG(input_uvc.c, input_init(), 302): input id: 0
 i: Using V4L2 device.: /dev/video0
 i: Desired Resolution: 720 x 576
 i: Frames Per Second.: 4
 i: Format............: YUYV
 i: JPEG Quality......: 80
 i: TV-Norm...........: PAL
 DBG(input_uvc.c, input_init(), 355): vdIn pn: 0
Setting FPS on the capture device is not supported, fallback to software framedropping
: Success
 i: Frame period time ......: 250 ms
 DBG(v4l2uvc.c, init_videoIn(), 96): Input name: Composite0
 DBG(v4l2uvc.c, init_videoIn(), 109): Current size: 720x576
 DBG(v4l2uvc.c, init_videoIn(), 138): Supported format: UYVY 4:2:2
 DBG(v4l2uvc.c, init_videoIn(), 178): current resolution: 255
 DBG(v4l2uvc.c, enumerateControls(), 988): V4L2 API's V4L2_CTRL_FLAG_NEXT_CTRL is supported
 DBG(v4l2uvc.c, control_readed(), 873): V4L2 parameter found: User Controls value 0 Class: USER
 DBG(v4l2uvc.c, control_readed(), 878): Unable to get the value of User Controls retcode: -1  Permission denied
 DBG(v4l2uvc.c, control_readed(), 873): V4L2 parameter found: Brightness value 0 Class: USER
 DBG(v4l2uvc.c, control_readed(), 873): V4L2 parameter found: Contrast value 0 Class: USER
 DBG(v4l2uvc.c, control_readed(), 873): V4L2 parameter found: Saturation value 0 Class: USER
 DBG(v4l2uvc.c, control_readed(), 873): V4L2 parameter found: Hue value 0 Class: USER
 DBG(v4l2uvc.c, control_readed(), 873): V4L2 parameter found: Chroma AGC value 0 Class: USER
 DBG(v4l2uvc.c, control_readed(), 873): V4L2 parameter found: Chroma Gain value 0 Class: USER
 DBG(v4l2uvc.c, enumerateControls(), 1023): JPEG compression details:
 DBG(v4l2uvc.c, enumerateControls(), 1024): Quality: 0
 DBG(v4l2uvc.c, enumerateControls(), 1025): APPn: 0
 DBG(v4l2uvc.c, enumerateControls(), 1026): APP length: 0
 DBG(v4l2uvc.c, enumerateControls(), 1027): APP data:
 DBG(v4l2uvc.c, enumerateControls(), 1028): COM length: 0
 DBG(v4l2uvc.c, enumerateControls(), 1029): COM data:
 o: www-folder-path...: ./www/
 o: HTTP TCP port.....: 9000
 o: username:password.: disabled
 o: commands..........: enabled
 DBG(input_uvc.c, input_run(), 400): launching camera thread #00

Then i tried to run commands below manually from build.sh, but again failed:

_+sudo apt-get -y install cmake
+sudo apt-get -y install libjpeg8-dev imagemagick libv4l-dev
+make
+sudo make install_

respond on command make was: 
_make: Nothing to be done for 'all'._

i can provide remore access via ssh

**Comment by jacksonliam** [comment]
You need to check out this specific pull request as I need to do more testing before I merge it and to use -u not -y in the command line.

**Comment by brunh** [comment]
./mjpg_streamer -i "./input_uvc.so -d /dev/video0 -u -f 4 -r 720x576 -n -t pal" -o "./output_http.so -w ./www -p 9000"

_UVC webcam grabber: unrecognized option '-u'_

**Comment by droberg** [comment]
Hello

@brunh, It seems that you are not running the version with the uvc-fix in
it.

@jacksonliam, I am currently on holiday for a week. Will get back to you
with a patch for the commentary after that.

Hälsningar
Per Öberg

2016-07-20 9:28 GMT+02:00 brunh <notifications@github.com>:

**Comment by droberg** [comment]
I submitted the changes in a new pull-request (see #31 )

**Pull request merged**
